### ISSUE TITLE
NetLicensing Demo: Class not found error

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensingClient-java#3]
After adding [NetLicensing](https://netlicensing.io) dependency to the pom.xml
```
  <dependency>
    <groupId>com.labs64.netlicensing</groupId>
    <artifactId>netlicensing-client</artifactId>
    <version>2.3.8</version>
  </dependency>
```

I'm getting following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/glassfish/jersey/client/ClientConfig
    at com.labs64.netlicensing.provider.RestProviderJersey.getClient(RestProviderJersey.java:119)
    at com.labs64.netlicensing.provider.RestProviderJersey.getTarget(RestProviderJersey.java:137)
    at com.labs64.netlicensing.provider.RestProviderJersey.call(RestProviderJersey.java:80)
    at com.labs64.netlicensing.service.NetLicensingService.request(NetLicensingService.java:204)
    at com.labs64.netlicensing.service.NetLicensingService.delete(NetLicensingService.java:160)
    at com.labs64.netlicensing.service.ProductService.delete(ProductService.java:140)
    at com.labs64.netlicensing.demo.NetLicensingClientDemo.main(NetLicensingClientDemo.java:385)
```

**Comment by r-brown** [comment]
## Using `netlicensing-client` dependency in IDE
Usually, your IDE (Eclipse or IntelliJ IDEA) is able to resolve all transitive dependencies of `netlicensing-client`.
Therefore all needed 3pp libraries and classes will be available in the classpath.

**Comment by r-brown** [comment]
## Using `netlicensing-client` dependency with Maven and CLI
Here is a step by step guideline on how to run NetLicensing Demo.

### Download NetLicensing Demo source code
Open NetLicensing [releases](https://github.com/Labs64/NetLicensingClient-java/releases) and download latest released version.

**Comment by r-brown** [comment]
## Download prepackaged version from sonatype.org

### Download compiled version
Download NetLicensing Demo packaged version ( netlicensing-client-demo-x.y.z.jar ) from https://oss.sonatype.org/content/repositories/releases/com/labs64/netlicensing/netlicensing-client-demo/ (use latest release version)

for example
```
$ wget https://oss.sonatype.org/content/repositories/releases/com/labs64/netlicensing/netlicensing-client-demo/2.3.8/netlicensing-client-demo-2.3.8.jar
```

### Run demo
Navigate to the download folder and execute following command:
```
$ java -jar netlicensing-client-demo-x.y.z.jar
  for instance
$ java -jar netlicensing-client-demo-2.3.8.jar
```

**Comment by r-brown** [comment]
The Issue cannot be reproduced anymore => close
